---
name: ssop
default_virtualization_engine: HyperV

admin_username: cs_admin
admin_password: New123Pass!
domain_info:
  domain_name: &DOMNAME ssop.local
lab_name: ssop
network_info:
  lab_subnet: 192.168.11.0/24
  role_ips:
    DC: 10
    SQL: 20
    WEB: 30
    RMQ: 40
    LNX: 50
    WIN: 60
sql:
  sqlsvcaccount: svc_sql
  sqlsvcpassword: New123Pass!
svrs:
  ssop-dc01:
    role: DC
    domain: *DOMNAME
  ssop-sql01:
    role: SQL
    domain: ssop.local
    memory: 4GB
    cpu: 2
  ssop-rmq01:
    role: RMQ
    domain: ssop.local
  ssop-rmq02:
    role: RMQ
    domain: ssop.local
  ssop-rmq03:
    role: RMQ
    domain: ssop.local
  ssop-web01:
    role: WEB
    domain: ssop.local
  ssop-web02:
    role: WEB
    domain: ssop.local
activeDirectory:
  ous:
    Service Accounts:
      Description: Holds Application Service Accounts
    Domain Users:
      Description: Holds Domain User Accounts
      children:
        Admins:
          Description: Holds Elevated Administrative User Accounts
        Others:
          Description: Holds other stuff
    Domain Groups:
      Description: Holds Groups of Domain Users and Service Accounts
  users:
    svc_vault_iis:
      Path: OU=Service Accounts
      Description: Used for Vault IIS Service
      DisplayName: Vault IIS Service
      Enabled: 1
      PasswordNeverExpires: 1
    svc_vault_sql:
      Path: OU=Service Accounts
      Description: Used for Vault SQL Service
      DisplayName: Vault SQL Service
      Enabled: 1
      PasswordNeverExpires: 1
    dkettman_adm:
      Path: OU=Admins,OU=Domain Users
      DisplayName: Dave Kettmann - Admin
      Enabled: 1
      PasswordNeverExpires: 1
